In [59]:
import matplotlib.pyplot as pyplot

import pandas as pandas

df1 = pandas.read_csv("./stack-overflow-developer-survey-2021/survey_results_public.csv",index_col="ResponseId")
df2 = pandas.read_csv("./stack-overflow-developer-survey-2020/survey_results_public.csv",index_col="Respondent")
df3 = pandas.read_csv("./stack-overflow-developer-survey-2019/survey_results_public.csv",index_col="Respondent")
df4 = pandas.read_csv("./stack-overflow-developer-survey-2018/survey_results_public.csv",index_col="Respondent")
df5 = pandas.read_csv("./stack-overflow-developer-survey-2017/survey_results_public.csv",index_col="Respondent")

C:\ProgramData\Miniconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (8,12,13,14,15,16,50,51,52,53,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [60]:
list_of_dfs = list()
list_of_dfs.append(df1)
list_of_dfs.append(df2)
list_of_dfs.append(df3)
list_of_dfs.append(df4)
list_of_dfs.append(df5)

list_of_dfs[0].head()

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,...,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,...,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,...,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,...,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,...,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,...,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN

In [61]:
df5['Gender'] == 'Male'

Respondent
1         True
2         True
3         True
4         True
5        False
         ...
51388     True
51389     True
51390    False
51391     True
51392     True
Name: Gender, Length: 51392, dtype: bool

In [73]:
df1.loc[df1.Gender=='Woman','Gender']='Female'
df2.loc[df2.Gender=='Woman','Gender']='Female'
df3.loc[df3.Gender=='Woman','Gender']='Female'
df1.loc[df1.Gender=='Man','Gender']='Male'
df2.loc[df2.Gender=='Man','Gender']='Male'
df3.loc[df3.Gender=='Man','Gender']='Male'

In [68]:
only_female = df5[df5['Gender'] == 'Female']
only_male = df5[df5['Gender'] == 'Male']
only_female

,Professional,ProgramHobby,Country,University,EmploymentStatus,FormalEducation,MajorUndergrad,HomeRemote,CompanySize,CompanyType,...,StackOverflowMakeMoney,Gender,HighestEducationParents,Race,SurveyLong,QuestionsInteresting,QuestionsConfusing,InterestedAnswers,Salary,ExpectedSalary
Respondent,,,,,,,,,,,,,,,,,,,,,
11,Professional non-developer who sometimes write...,"Yes, I program as a hobby",United States,No,Employed full-time,Bachelor's degree,A social science,All or almost all the time (I'm full-time remote),100 to 499 employees,Venture-funded startup,...,Strongly disagree,Female,"Some college/university study, no bachelor's d...",White or of European descent,Strongly disagree,Agree,Strongly disagree,Strongly agree,NaN,NaN
14,Professional developer,"Yes, both",Germany,No,Employed full-time,Some college/university study without earning ...,Computer science or software engineering,"Less than half the time, but at least one day ...",Fewer than 10 employees,Venture-funded startup,...,Disagree,Female,A master's degree,Hispanic or Latino/Latina,Somewhat agree,Agree,Disagree,Strongly agree,NaN,NaN
104,Professional developer,No,United States,No,Employed full-time,Bachelor's degree,Something else,Never,20 to 99 employees,"Privately-held limited company, not in startup...",...,Disagree,Female,A bachelor's degree,White or of European descent,Somewhat agree,Agree,Disagree,Agree,51000.000000,NaN
166,Professional developer,"Yes, I program as a hobby",Germany,No,Employed full-time,Some college/university study without earning ...,Something else,A few days each month,"10,000 or more employees","Privately-held limited company, not in startup...",...,NaN,Female,"Some college/university study, no bachelor's d...",White or of European descent,Agree,Somewhat agree,Somewhat agree,Somewhat agree,NaN,NaN
215,Professional developer,"Yes, I contribute to open source projects",Germany,No,Employed full-time,Master's degree,Computer science or software engineering,A few days each month,"5,000 to 9,999 employees",Pre-series A startup,...,Somewhat agree,Female,A doctoral degree,White or of European descent,Strongly agree,Somewhat agree,Strongly disagree,Strongly agree,51612.903226,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51322,Student,"Yes, I contribute to open source projects",Malaysia,"Yes, full-time","Independent contractor, freelancer, or self-em...",Some college/university study without earning ...,Computer science or software engineering,"Less than half the time, but at least one day ...",NaN,NaN,...,Disagree,Female,"Some college/university study, no bachelor's d...",NaN,Agree,Strongly agree,Disagree,Somewhat agree,NaN,336.32287
51346,Professional developer,No,United Kingdom,No,Employed full-time,Doctoral degree,A non-computer-focused engineering discipline,A few days each month,100 to 499 employees,"Privately-held limited company, not in startup...",...,Disagree,Female,A master's degree,White or of European descent,Somewhat agree,Agree,Disagree,Agree,NaN,NaN
51357,Professional developer,"Yes, I contribute to open source projects",Portugal,No,Employed full-time,Master's degree,Computer science or software engineering,Never,20 to 99 employees,"Privately-held limited company, not in startup...",...,Agree,Female,A bachelor's degree,White or of European descent,Strongly agree,Agree,Disagree,Strongly agree,15483.870968,NaN
51368,Student,"Yes, both",Spain,"Yes, full-time",Employed part-time,Bachelor's degree,Computer engineering or electrical/electronics...,About half the time,I don't know,"Sole proprietorship or partnership, not in sta...",...,Disagree,Female,A bachelor's degree,Hispanic or Latino/Latina; White or of Europea...,Somewhat agree,Somewhat agree,Strongly disagree,Agree,NaN,NaN
51386,Used to be a professional developer,"Yes, both",United Kingdom,No,Employed full-time,Master's degree,A business discipline,A few days each month,"1,000 to 4,999 employees",Government agency or public school/university,...,Somewhat agree,Female,High school,White or of European descent,Somewhat agree,Strongly agree,Disagree,Strongly agree,NaN,NaN

In [82]:
def counter(df):
    only_female = df[df['Gender'] == 'Female']
    only_male = df[df['Gender'] == 'Male']
    
    number_of_female = len(only_female)
    number_of_male = len(only_male)
    gesamt = len(df)
    
    counts = {
        'female': number_of_female,
        'male': number_of_male,
        'gesamt': gesamt
    }
    
    return counts

number = counter(df5)
    
print("Female: " + str(number['female']) + " --- Male: " + str(number['male']) + " --- Insgesamt: " + str(number['gesamt']))

Female: 2600 --- Male: 31589 --- Insgesamt: 51392

In [86]:
list = []

for df in list_of_dfs:
    numbers = counter(df)
    list.append(numbers)
    
print(list)
# faengt mit neuestem Datensatz an

[{'female': 4120, 'male': 74817, 'gesamt': 83439}, {'female': 3844, 'male': 46013, 'gesamt': 64461}, {'female': 6344, 'male': 77919, 'gesamt': 88883}, {'female': 4025, 'male': 59458, 'gesamt': 98855}, {'female': 2600, 'male': 31589, 'gesamt': 51392}]

In [120]:
data = {
    'Jahr': ['2021', '2020', '2019', '2018', '2017'],
    'Frauen': [list[0]['female'], list[1]['female'], list[2]['female'], list[3]['female'], list[4]['female']],
    'Gesamtzahl': [list[0]['gesamt'], list[1]['gesamt'], list[2]['gesamt'], list[3]['gesamt'], list[4]['gesamt']] 
}
df = pandas.DataFrame(data=data)

In [121]:
df.head()

   Jahr  Frauen  Gesamtzahl
0  2021    4120       83439
1  2020    3844       64461
2  2019    6344       88883
3  2018    4025       98855
4  2017    2600       51392

In [122]:
df.to_csv('frauenanteil_so.csv')

In [57]:
df['2020'].size

83439

In [44]:
df['2021'].value_counts()

Man                                                                                   74817
Woman                                                                                  4120
Prefer not to say                                                                      1442
Non-binary, genderqueer, or gender non-conforming                                       690
Or, in your own words:                                                                  413
Man;Or, in your own words:                                                              268
Man;Non-binary, genderqueer, or gender non-conforming                                   252
Woman;Non-binary, genderqueer, or gender non-conforming                                 147
Man;Woman                                                                                41
Non-binary, genderqueer, or gender non-conforming;Or, in your own words:                 21
Man;Woman;Non-binary, genderqueer, or gender non-conforming                              21
Man;Woman;Non-binary, genderqueer, or gender non-conforming;Or, in your own words:       17
Woman;Or, in your own words:                                                             16
Man;Non-binary, genderqueer, or gender non-conforming;Or, in your own words:             11
Woman;Non-binary, genderqueer, or gender non-conforming;Or, in your own words:            9
Man;Woman;Or, in your own words:                                                          1
Name: 2021, dtype: int64